### ISSUE TITLE
the sample does not work

### ISSUE THREAD

**Issue by valentinvieriu** [rtlee9/Trump-bot#1]
Hi,
I've tried to use the docker image that you provided. It does not seem to be up to date with the master, but I've pulled the latest changes but it does not work.
After following your advice and pulling `docker pull rtlee/t-bot:sample`
and then `docker run -t -i rtlee/t-bot:sample /bin/bash` an inside doing a `git pull origin master`:

I'm getting this error:

```
root@50c4d25c2c16:~/Trump-bot# python sample.py "I will build a"
Traceback (most recent call last):
  File "sample.py", line 109, in <module>
    print sampler.get_sample()
  File "sample.py", line 71, in get_sample
    'char', self.seed, self.char_temperature, 300)
  File "sample.py", line 42, in get_sample_raw
    '-primetext', seed
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['th', 'sample.lua', 'cv/char-rnn-trained.t7', '-temperature', '0.4', '-length', '300', '-gpuid', '-1', '-primetext', 'I will build a']' returned non-zero exit status -4
```

If I try to run only `th sample.lua cv/char-rnn-trained.t7 -temperature 0.4 -length 300 -gpuid -1 -primetext "I will build a"` I'm getting:

```
creating an lstm...
seeding with I will build a
--------------------------
Illegal instruction (core dumped)
```

**Comment by rtlee9** [comment]
Hi @valentinvieriu,

Thanks for pointing this out. The docker build cached my repo causing the sampling script to become outdated as I continued to push onto that repo. I've rebuilt the container for future pullers and added a note to the readme in case anyone else has run into this.

Please let me know if it doesn't run if you do either of the following:

1. Run `git pull origin master` from your existing container
2. Re-pull the container from the hub

**Comment by valentinvieriu** [comment]
Thank you for updating the image. I've pulled the latest image, and also did a git pull inside of the image but the result is the same.
The sample.py script fails with the same error:
```
root@b7273a042875:~/Trump-bot# python sample.py "I will build a"
Traceback (most recent call last):
  File "sample.py", line 109, in <module>
    print sampler.get_sample()
  File "sample.py", line 71, in get_sample
    'char', self.seed, self.char_temperature, 300)
  File "sample.py", line 42, in get_sample_raw
    '-primetext', seed
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['th', 'sample.lua', 'cv/char-rnn-trained.t7', '-temperature', '0.4', '-length', '300', '-gpuid', '-1', '-primetext', 'I will build a']' returned non-zero exit status -4
```

I don't think that the sample.py is  the problem. When I run manually `th sample.lua cv/char-rnn-trained.t7 -temperature 0.4 -length 300 -gpuid -1 -primetext "I will build a"` - i assume this is the intended command line to be run by the sample.py, I'm still getting the same error.

```
root@b7273a042875:~/Trump-bot# th sample.lua cv/char-rnn-trained.t7 -temperature 0.4 -length 300 -gpuid -1 -primetext "I will build a"
creating an lstm...
seeding with I will build a
--------------------------
Illegal instruction (core dumped)
```

Any suggestion is welcomed. I've even tried to run this by using nvidia-docker, assuming that the container expects GPU to be enabled ( I doubt this, because in all of your scripts you are forcing gpu = -1 )


To clarify, I"m using there rtlee/t-bot:sample image.
```
Pull docker image: docker pull rtlee/t-bot:sample
Run docker container: docker run -t -i rtlee/t-bot:sample /bin/bash
Update the git repo: git pull origin master
Sample from models: python sample.py "I will build a"
```

I've also tried with the rtlee/t-bot: train and no success either. For the sample.py I've get the same error, and if I try to run the training `./train_char.sh` I'm getting this error.

```
root@e3578019f4b9:~/Trump-bot# ./train_char.sh
vocab.t7 or data.t7 detected as stale. Re-running preprocessing...
one-time setup: preprocessing input text file data/trump/input_norm_caps/input.txt...
loading text file...
creating vocabulary mapping...
word occurence threshold is 0
putting data into tensor...
saving data/trump/input_norm_caps/vocab.t7
saving data/trump/input_norm_caps/data.t7
loading data files...
cutting off end of data so that the batches/sequences divide evenly
reshaping tensor...
data load done. Number of data batches in train: 484, val: 26, test: 0
vocab size: 82
creating an lstm with 3 layers
using optimizer rmsprop
setting forget gate biases to 1 in LSTM layer 1
setting forget gate biases to 1 in LSTM layer 2
setting forget gate biases to 1 in LSTM layer 3
number of parameters in the model: 1421906
cloning rnn
cloning criterion
./train_char.sh: line 12:    52 Illegal instruction     (core dumped) th train.lua -gpuid -1 -data_dir data/trump/input_norm_caps -max_epochs 60 -print_every 25 -rnn_size 256 -num_layers 3 -dropout 0.4 -eval_val_every 2000 -checkpoint_dir cv_char_caps_256_3
```
Thank you

**Comment by rtlee9** [comment]
Got it. Unfortunately I haven't been able to reproduce the error on various Linux based machines (OSX, Ubuntu VM, AWS Ubuntu instance, AWS Amazon Linux instance), but based on [this issue](https://github.com/Theano/Theano/issues/4783) and [this thread](https://groups.google.com/forum/#!topic/theano-users/8uAXgeTEbN0) it seems like updating your ~/.theanorc (presumably within the container) with one of the following is most likely to do the trick:
```
[gcc]
gcc.cxxflags='-march=corei7"
gcc.cxxflags='-march=core2"
gcc.cxxflags='-march=corei7-avx"
```

If you want to give it a go on an AWS EC2 instance, you can follow steps 1-8 [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html#install_docker) and then follow the steps on my readme. Let me know if that resolves it.

**Comment by valentinvieriu** [comment]
@rtlee9 tried the configuration that you have mentioned, but still does not work. I don't want to use an amazon  gpu instance, I have my own server, with a Nvidia GTX960 card.
Is it possible to share the Docker image you are using on the Amazon? I would try to rebuild the image myself.

Thank you

**Comment by rtlee9** [comment]
@valentinvieriu sure thing - the Dockerfile for training can be found [here](https://github.com/rtlee9/word-rnn-docker/blob/t-bot/Dockerfile), and the Dockerfile for sampling only can be found [here](https://github.com/rtlee9/word-rnn-docker/blob/sample/Dockerfile). The only difference is the sampling-only version doesn't pull the GloVe files needed for fitting using pre-trained vectors.

**Comment by valentinvieriu** [comment]
Thank you @rtlee9 . I've manged to make it work. I'm using a different image as a starting point `FROM nvidia/cuda:8.0-cudnn5-devel`

By using this image, you make sure you can use the GPU acceleration inside Dcoker using nvidia-docker.

I will optimise the image for size ( right now I've just wanted to make sure it works ) and then share it with you.

Thank you again for the support
