### ISSUE TITLE
How can you run the training with GPU enabled?

### ISSUE THREAD

**Issue by valentinvieriu** [rtlee9/Trump-bot#2]
Does the provided Docker [image](https://hub.docker.com/r/rtlee/t-bot/tags/) supports training withe the GPU enabled? If yes, can you share the procedure?

I've tried using the [nvidia-docker](https://github.com/NVIDIA/nvidia-docker), and then forcing the gpu flag to be 0, but I'm getting error regarding missing some packages. And ofcourse running it on the CPU does not work #1 

```
root@3c6c0bb3a66e:~/Trump-bot# th sample.lua cv/char-rnn-trained.t7 -temperature 0.4 -length 300 -gpuid 0 -primetext "I will build a"
package cunn not found!
package cutorch not found!
Falling back on CPU mode
creating an lstm...
seeding with I will build a
--------------------------
Illegal instruction (core dumped)
```
Is it possible to share the Docker image too ( the Dockersource file ) in the repo? Also would you consider a good idea to use [already prepared images](https://hub.docker.com/r/nvidia/cuda/) as a starting point?

Thank you

**Comment by rtlee9** [comment]
I'm fairly certain this is tied to #1, but I could be wrong. I am able to train with GPU using this image in three steps:
1. Spin up an EC2 g2.2xlarge instance
2. Install the NVIDIA drivers and Docker if not pre-installed on your image
3. Follow the steps on the readme

**Comment by rtlee9** [comment]
Might be worth revisiting after #1 is resolved.
